# Generated by Django 4.2.7 on 2026-08-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published',
        ),
    ]
